### ISSUE TITLE
Internal Server Error: Property "Craft\EntryModel.owner" is not defined.

### ISSUE THREAD

**Issue by alexv9** [engram-design/Comments#55] opened 2016-09-30 12:27 UTC
Hi there,

I installed your latest release in craft 2.6.2945, my php version is 5.6.
When I want to add a new comment in the frontend I get the following error message:

Internal Server Error
Property "Craft\EntryModel.owner" is not defined.

In my logs I could find the following:
exception 'CException' with message 'Property "Craft\EntryModel.owner" is not defined.' in /craft/app/framework/base/CComponent.php:130

Any idea what went wrong?

**Comment by andreasbecker** [comment] 2016-09-30 15:51
same here

**Comment by jamiecmm** [comment] 2016-10-02 13:22
Just had this issue myself. I've reverted back to to 0.4.5 and that works as expected.

Anyone that needs it, I've attached that version.
[Comments-0.4.5.zip](https://github.com/engram-design/Comments/files/504954/Comments-0.4.5.zip)

**Comment by jamiecmm** [comment] 2016-10-02 13:25
I'm only using this on a live site, so I don't have a dev environment to test and submit a PR, but it looks like the issue is line 414 in comments/services/CommentsService.php

I'm guessing changing it to `if (isset($element->owner->author) && isset($element->owner))` would do it

**Comment by engram-design** [comment] 2016-10-09 12:35
Sorry for the delay in fixing this - fixed in [0.4.7](https://github.com/engram-design/Comments/releases/tag/0.4.7).

**Closed by engram-design** 2016-10-09 12:35 UTC
